/* Writing Task 1/2 HTML practice simulators.
   Extracted from the route so the data can be shared with the admin
   content registry (src/lib/content-registry.ts) as well as the page. */

export type HtmlTask = {
  id: string;
  task: 1 | 2;
  type: string;
  title: string;
  description: string;
  image?: string;
  htmlFile: string;
  prompt?: string;
  minWords?: number;
  timeMinutes?: number;
  isNew?: boolean;
  /** Force this simulator to stay free regardless of the default free-slice policy. */
  isFree?: boolean;
};

export const HTML_TASKS: HtmlTask[] = [
  // Cambridge IELTS 20 – Writing Task 1
  {
    id: "cam20-t1-task1",
    task: 1,
    type: "Bar Chart",
    title: "Cambridge 20 Test 1 – Writing Task 1",
    description: "Cambridge IELTS 20 Test 1 Writing Task 1: describe the bar chart and summarise the main features.",
    image: "/writing-images/cam20_test1_task1.jpeg",
    htmlFile: "/writing/CAM20_TEST_1_Task1.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
  },
  {
    id: "cam20-t2-task1",
    task: 1,
    type: "Map",
    title: "Cambridge 20 Test 2 – Writing Task 1",
    description: "Cambridge IELTS 20 Test 2 Writing Task 1: describe the floor plans of a library in 2005 and 2023.",
    image: "/writing-images/cam20_test2_task.jpeg",
    htmlFile: "/writing/CAM20_TEST_2_Task1.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
  },
  {
    id: "cam20-t3-task1",
    task: 1,
    type: "Line Graph",
    title: "Cambridge 20 Test 3 – Writing Task 1",
    description: "Cambridge IELTS 20 Test 3 Writing Task 1: summarise the information shown in the chart.",
    image: "/writing-images/cam20_test3_task1.jpeg",
    htmlFile: "/writing/CAM20_TEST_3_Task1.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
  },
  {
    id: "cam20-t4-task1",
    task: 1,
    type: "Mixed",
    title: "Cambridge 20 Test 4 – Writing Task 1",
    description: "Cambridge IELTS 20 Test 4 Writing Task 1: summarise the information shown in the chart.",
    image: "/writing-images/cam20_test4_task1.jpeg",
    htmlFile: "/writing/CAM20_TEST_4_Task1.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
  },
  {
    id: "html-t1-water-use",
    task: 1,
    type: "Pie Chart",
    title: "Residential Water Use",
    description: "The charts below show information on residential water use in 1988 and 2008.",
    image: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&q=80",
    htmlFile: "/passages/task1_1.html",
  },
  {
    id: "html-t1-water-use-purposes",
    task: 1,
    type: "Table",
    title: "Water use purposes",
    description: "The table below shows water use for different purposes in four countries.",
    image: "/writing-images/task1_12.jpg",
    htmlFile: "/passages/task1_12.html",
  },
  {
    id: "html-t1-tourist-numbers-to-ausralia",
    task: 1,
    type: "Mixed",
    title: "Tourist numbers to Australia and Types of travel",
    description:
      "The charts below show the number of tourists to Australia and the types of travels between 1995 and 2005.",
    image: "/writing-images/task1_10.jpg",
    htmlFile: "/passages/task1_10.html",
  },
  {
    id: "html-t1-unemployment-levels-in-ireland",
    task: 1,
    type: "Line Graph",
    title: "Unemployment and Emigration in Ireland",
    description:
      "The graph below shows unemployment levels in Ireland and the number of people leaving the country between 1988 and 2008.",
    image: "/writing-images/task1_11.jpg",
    htmlFile: "/passages/task1_11.html",
  },
  {
    id: "html-t1-female-parliament-members",
    task: 1,
    type: "Line Graph",
    title: "Female Members of Parliament",
    description:
      "The graph shows the percentage of female members of parliament in five European countries from 2000 to 2012.",
    image: "/writing-images/government_funding.png",
    htmlFile: "/passages/task1_2.html",
  },
  {
    id: "html-t1-uk-steel-industry",
    task: 1,
    type: "Line Graph",
    title: "UK Steel Industry",
    description:
      "The line graphs show changes in UK steel demand, production, imports and employment from 1970 to 2000.",
    image: "/writing-images/task3.jpg",
    htmlFile: "/passages/task1_3.html",
  },
  {
    id: "html-t1-uk-steel-employment",
    task: 1,
    type: "Mixed",
    title: "Value Changes and Employment in the UK Steel Industry",
    description:
      "The charts illustrate value changes and employment status in the UK steel industry between 1970 and 2000.",
    image: "/writing-images/task1_3.jpg",
    htmlFile: "/passages/task1_4.html",
  },
  {
    id: "html-t1-clothing-import-prices",
    task: 1,
    type: "Bar Chart",
    title: "Average Price of Imported Clothing",
    description:
      "The bar chart compares the average cost of clothing imported into the European Union from six countries in 1997 and 2003.",
    image: "/writing-images/task1_4.jpg",
    htmlFile: "/passages/task1_5.html",
  },
  {
    id: "html-t1-milk-production",
    task: 1,
    type: "Table",
    title: "Milk Production in Four Countries",
    description:
      "The table shows the production of milk in the Netherlands, Australia, Tanzania and Guatemala in 1990, 2000 and 2010.",
    image: "/writing-images/task1_6.jpg",
    htmlFile: "/passages/task1_6.html",
  },
  {
    id: "html-t1-milk-production-countries",
    task: 1,
    type: "Table",
    title: "Annual Milk Production",
    description:
      "The table compares annual milk production in four countries across three years: 1990, 2000 and 2010.",
    image: "/writing-images/task1_7.jpg",
    htmlFile: "/passages/task1_7.html",
  },
  {
    id: "html-t1-aluminium-recycling",
    task: 1,
    type: "Process",
    title: "Recycling Aluminium Drink Cans",
    description:
      "The diagram shows the stages in the recycling of aluminium drink cans over a six-week process.",
    image: "/writing-images/task1_8.jpg",
    htmlFile: "/passages/task1_8.html",
  },
  {
    id: "html-t1-communication-methods",
    task: 1,
    type: "Line Graph",
    title: "Communication Methods",
    description:
      "The line graph shows the percentage of people who used five different communication methods between 1998 and 2008.",
    image: "/writing-images/task1_9.jpg",
    htmlFile: "/passages/task1_9.html",
  },
  {
    id: "html-t1-films-and-ticket-sales",
    task: 1,
    type: "Bar Chart",
    title: "Films Released and Cinema Ticket Sales",
    description:
      "The charts show the percentages of films released and cinema ticket sales by genre in 1996 and 2000.",
    image: "/writing-images/task1_10.jpg",
    htmlFile: "/passages/task1_10.html",
  },
  {
    id: "html-t1-prison-population-europe",
    task: 1,
    type: "Line Graph",
    title: "Prison Population in Europe",
    description:
      "The line graph shows the prison population in a European country between 1911 and 2001.",
    image: "/writing-images/task1_13.jpg",
    htmlFile: "/passages/task1_13.html",
  },
  {
    id: "html-t1-noise-pollution",
    task: 1,
    type: "Bar Chart",
    title: "Noise Pollution Effects",
    description: "The chart shows the number of people affected by noise pollution.",
    image: "/writing-images/task_14.jpg",
    htmlFile: "/passages/task1_14.html",
  },
  {
    id: "html-t1-american-japanese-office",
    task: 1,
    type: "Diagram",
    title: "American and Japanese Office",
    description: "The diagrams below show a typical American and a Japanese office.",
    image: "/writing-images/task1_15.jpg",
    htmlFile: "/passages/task1_15.html",
  },
  {
    id: "html-t1-universities-canada",
    task: 1,
    type: "Bar Chart",
    title: "Academic and Employment Statistics – Canadian Universities",
    description:
      "The chart below gives information on different academic and employment statistics for three universities in Canada.",
    image: "/writing-images/task1_16.jpg",
    htmlFile: "/passages/task1_16.html",
  },
  {
    id: "html-t1-brindell-town-development",
    task: 1,
    type: "Map",
    title: "Development of Brindell Town",
    description:
      "The diagrams below show the development of a town called Brindell and the local areas in 1800, 1900 and 2000.",
    image: "/writing-images/task1_17.jpg",
    htmlFile: "/passages/task1_17.html",
  },
  {
    id: "html-t1-motorbike-licenses",
    task: 1,
    type: "Bar Chart",
    title: "Motorbike Driving Licences by Gender",
    description:
      "The chart shows the percentage of male and female who had driving licenses for motorbikes in one European country.",
    image: "/writing-images/task1_18.jpg",
    htmlFile: "/passages/task1_18.html",
  },
  {
    id: "html-t1-patient-service-ratings",
    task: 1,
    type: "Table",
    title: "Patient Service Ratings",
    description:
      "The table below shows the percentage of patients saying the service was very good.",
    image: "/writing-images/task1_19.jpg",
    htmlFile: "/passages/task1_19.html",
  },
  {
    id: "html-t1-marriage-australia",
    task: 1,
    type: "Table",
    title: "Marriage Status and Age in Australia",
    description:
      "The table below provides information on marriage status and age from 1960 to 2000 in Australia.",
    image: "/writing-images/task1_20.jpg",
    htmlFile: "/passages/task1_20.html",
  },
  {
    id: "html-t1-tourism-jobs-uk",
    task: 1,
    type: "Bar Chart",
    title: "Tourism Jobs in a UK City",
    description:
      "The chart below shows the number of jobs in tourism-related industry in one UK city between 1989 and 2009.",
    image: "/writing-images/task1_21.jpg",
    htmlFile: "/passages/task1_21.html",
  },
  {
    id: "html-t1-coal-fired-power-station",
    task: 1,
    type: "Diagram",
    title: "Coal-Fired Power Station",
    description:
      "The diagram below shows how the electricity is produced through a coal-fired power station.",
    image: "/writing-images/task1_22.jpg",
    htmlFile: "/passages/task1_22.html",
  },
  {
    id: "html-t1-spending-categories-australia",
    task: 1,
    type: "Line Graph",
    title: "Spending Categories in Australia",
    description:
      "The graph below shows the percentage of total spending in five different categories from 1970 to 2010 in one city in Australia.",
    image: "/writing-images/task1_23.jpg",
    htmlFile: "/passages/task1_23.html",
  },
  {
    id: "html-t1-tea-coffee-imports",
    task: 1,
    type: "Bar Chart",
    title: "Tea and Coffee Imports",
    description:
      "The graph below shows the amount of tea and coffee imported by four different countries in tonnes in 2007.",
    image: "/writing-images/task1_24.jpg",
    htmlFile: "/passages/task1_24.html",
  },
  {
    id: "html-t1-technology-aid-charities",
    task: 1,
    type: "Table",
    title: "Technology Aid by Charities",
    description:
      "The table shows the amount of money given in aid of developing countries' technology by charities in the US, EU, and other countries from 2006 to 2010.",
    image: "/writing-images/task1_25.jpg",
    htmlFile: "/passages/task1_25.html",
  },
  // Cambridge IELTS 21 – Writing Task 2
  {
    id: "cam21-t1-task2",
    task: 2,
    type: "Agree/Disagree",
    title: "Cambridge 21 Test 1 – Writing Task 2",
    description:
      "Cambridge IELTS 21 Test 1 Writing Task 2: whether building tall apartment blocks is the best way to provide enough homes in large cities.",
    prompt:
      "The best way to provide enough homes in large cities is to build tall apartment blocks.\nTo what extent do you agree or disagree with this statement?",
    image: "",
    htmlFile: "/writing/CAM21_TEST_1_Task2.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "cam21-t2-task2",
    task: 2,
    type: "Discussion",
    title: "Cambridge 21 Test 2 – Writing Task 2",
    description:
      "Cambridge IELTS 21 Test 2 Writing Task 2: whether theatres and cinemas are still important in the digital age or no longer needed because entertainment is available online.",
    prompt:
      "Some people say that in the digital age, theatres and cinemas are no longer as important as people can watch all the entertainment they want online. Others argue that theatres and cinemas are still important both economically and culturally.\nDiscuss both these views and give your own opinion.",
    image: "",
    htmlFile: "/writing/CAM21_TEST_2_Task2.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "cam21-t3-task2",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Cambridge 21 Test 3 – Writing Task 2",
    description:
      "Cambridge IELTS 21 Test 3 Writing Task 2: whether the advantages of requiring all undergraduate courses to include study abroad or a work placement outweigh the disadvantages.",
    prompt:
      "All university undergraduate courses should include a period of time spent studying abroad or doing a work placement.\nDo you think the advantages of this would outweigh the disadvantages?",
    image: "",
    htmlFile: "/writing/CAM21_TEST_3_Task2.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "cam21-t4-task2",
    task: 2,
    type: "Two-Part Question",
    title: "Cambridge 21 Test 4 – Writing Task 2",
    description:
      "Cambridge IELTS 21 Test 4 Writing Task 2: whether primary schools focus too much on formal learning, and how important it is for children to play as well as learn.",
    prompt:
      "Some people argue that primary schools focus too much on formal learning.\nTo what extent do you agree with this opinion?\nHow important do you think it is for children to play as well as learn in the primary school classroom?",
    image: "",
    htmlFile: "/writing/CAM21_TEST_4_Task2.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_1",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Home Education vs Schooling",
    description:
      "A Task 2 essay about whether educating children at home has more advantages than disadvantages compared with formal schooling.",
    prompt:
      "In some countries, many people choose to educate children at home by themselves instead of sending them to school.\nDo you think the advantages outweigh the disadvantages?",
    image: "",
    htmlFile: "/writing/task2_1.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_2",
    task: 2,
    type: "Agree/Disagree",
    title: "Younger Leaders in Organizations",
    description:
      "A Task 2 essay about whether younger people would make better leaders and directors in organizations.",
    prompt:
      "Leaders and directors in an organization are normally older people. Some people think younger leaders would be better.\nDo you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_2.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_3",
    task: 2,
    type: "Agree/Disagree",
    title: "Watching Live Performances Online",
    description:
      "A Task 2 essay about whether watching live performances online is preferable to attending events in person.",
    prompt:
      "These days people prefer to watch live performances, such as shows and concerts, on TV or computer online rather than go to the place of that event.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_3.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_4",
    task: 2,
    type: "Agree/Disagree",
    title: "Group Activities and Life Skills",
    description:
      "A Task 2 essay about whether team activities teach more important life skills than individual activities.",
    prompt:
      "Group or team activities can teach more important skills for life than activities which are done alone.\nDo you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_4.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_5",
    task: 2,
    type: "Discussion",
    title: "Women in Police and Military Forces",
    description:
      "A Task 2 discussion essay about whether women should have equal roles in the police and military.",
    prompt:
      "Some people believe that women should play an equal role to men in a country's police force or military force such as the army, while others think women are not suitable for this kind of job.\nDiscuss both views and give your opinion.",
    image: "",
    htmlFile: "/writing/task2_5.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_6",
    task: 2,
    type: "Agree/Disagree",
    title: "Public Spaces in Towns and Cities",
    description:
      "A Task 2 essay about the importance of large public spaces such as squares and parks in urban areas.",
    prompt:
      "It is important for all towns and cities to have large public spaces such as squares and parks.\nTo what extent do you agree or disagree with this statement?",
    image: "",
    htmlFile: "/writing/task2_6.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_7",
    task: 2,
    type: "Agree/Disagree",
    title: "Copying Others in Fashion and Consumer Goods",
    description:
      "A Task 2 essay about whether fashion and consumer goods show that people naturally copy one another.",
    prompt:
      "The tendency of human beings to copy one another is shown in the popularity of areas such as fashion and consumer goods.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_7.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_8",
    task: 2,
    type: "Positive/Negative Development",
    title: "Internet as a Source of World News",
    description:
      "A Task 2 essay about whether using the internet instead of newspapers and TV for world news is a positive or negative change.",
    prompt:
      "Nowadays, people use the internet instead of newspapers and TV programs to learn about world news.\nIs this a positive or negative development?",
    image: "",
    htmlFile: "/writing/task2_8.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_9",
    task: 2,
    type: "Agree/Disagree",
    title: "Traditional Ideas and Modern Life",
    description:
      "A Task 2 essay about whether traditional ideas from older generations are useful for preparing young people for modern life.",
    prompt:
      "The older generations tend to have very traditional ideas about how people should live, think and behave. However, some people believe that these ideas are not helpful in preparing younger generations for modern life.\nTo what extent do you agree or disagree with this view?",
    image: "",
    htmlFile: "/writing/task2_9.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_10",
    task: 2,
    type: "Agree/Disagree",
    title: "Family Values and School Knowledge",
    description:
      "A Task 2 essay about whether school knowledge is more important than family values for children’s success.",
    prompt:
      "Learning values from parents and family is important in children’s success, but knowledge gained at school is more important.\nDo you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_10.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_11",
    task: 2,
    type: "Discussion",
    title: "International Business and National Identity",
    description:
      "A Task 2 discussion essay about whether international business contact benefits people or harms national identity.",
    prompt:
      "Many people go to other countries to do business and contact with people. While some think that this contact is positive, others believe that it has a negative impact on the identities of citizens.\nDiscuss both views and give your own opinion.",
    image: "",
    htmlFile: "/writing/task2_11.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_12",
    task: 2,
    type: "Agree/Disagree",
    title: "Longer Holidays for Employees",
    description:
      "A Task 2 essay about whether longer annual holidays improve employees’ performance at work.",
    prompt:
      "Employers should give their staff at least four weeks of holiday in a year, as longer holidays make employees better at their job.\nTo what extent do you agree or disagree? Give any relevant examples or experience.",
    image: "",
    htmlFile: "/writing/task2_12.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_13",
    task: 2,
    type: "Problem/Solution",
    title: "Unhealthy Eating Habits and Obesity",
    description:
      "A Task 2 cause-and-solution essay about unhealthy eating habits, obesity, and ways to improve diets.",
    prompt:
      "In many countries, people's eating habits are leading to obesity and other health problems.\nWhy do so many people have unhealthy eating habits? What is the most effective way to help people improve their eating habits?",
    image: "",
    htmlFile: "/writing/task2_13.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_14",
    task: 2,
    type: "Positive/Negative Development",
    title: "Affordable International Travel",
    description:
      "A Task 2 essay about whether easier and more affordable international travel is a positive or negative development.",
    prompt:
      "It has become easier and more affordable for people to visit other countries.\nIs it a positive or negative development?",
    image: "",
    htmlFile: "/writing/task2_14.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_15",
    task: 2,
    type: "Agree/Disagree",
    title: "More Good News in the Media",
    description: "A Task 2 essay about whether news media should report more positive stories.",
    prompt:
      "The media should include more stories which report good news.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_15.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_16",
    task: 2,
    type: "Agree/Disagree",
    title: "Fashion and Consumer Goods",
    description:
      "A Task 2 essay about whether the popularity of fashion and consumer goods proves that people copy each other.",
    prompt:
      "The tendency for human beings to copy one another is shown in the popularity of fashion in clothes and other consumer goods.\nDo you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_16.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_17",
    task: 2,
    type: "Agree/Disagree",
    title: "Understanding Cultures Through Multinational Work",
    description:
      "A Task 2 essay about whether working for a multinational organisation is the best way to understand other cultures.",
    prompt:
      "The best way to understand other cultures is working for a multinational organisation.\nDo you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_17.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_18",
    task: 2,
    type: "Problem/Solution",
    title: "Fewer Students Choosing Science",
    description:
      "A Task 2 cause-and-effect essay about why fewer students choose science subjects and how this affects society.",
    prompt:
      "It is observed that in many countries not enough students are choosing to study science subjects.\nWhat are the causes of this trend, and what are the effects on society?",
    image: "",
    htmlFile: "/writing/task2_18.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_19",
    task: 2,
    type: "Agree/Disagree",
    title: "Technology and Free Time",
    description:
      "A Task 2 essay about whether modern technology has really given people more free time.",
    prompt:
      "It was predicted that with the development of technology, people in the 21st century would have much more free time than in the past.\nTo what extent has this prediction come true?",
    image: "",
    htmlFile: "/writing/task2_19.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_20",
    task: 2,
    type: "Agree/Disagree",
    title: "Good News Stories in the Media",
    description:
      "A Task 2 essay about whether media organisations should include more good news stories.",
    prompt:
      "The media should include more stories which report good news.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_20.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_21",
    task: 2,
    type: "Two-Part Question",
    title: "Travelling to Other Countries",
    description:
      "A Task 2 two-part essay about why people travel abroad and whether this trend is positive or negative.",
    prompt:
      "Many people are travelling to other countries.\nWhy? Is it a positive or negative development?",
    image: "",
    htmlFile: "/writing/task2_21.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_22",
    task: 2,
    type: "Problem/Solution",
    title: "Problems of Growing Major Cities",
    description:
      "A Task 2 problem-and-solution essay about the challenges caused by the growth of major cities.",
    prompt:
      "As major cities continue to grow, so do their problems.\nWhat problems may this cause? What are the solutions for these problems?",
    image: "",
    htmlFile: "/writing/task2_22.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_23",
    task: 2,
    type: "Two-Part Question",
    title: "The Growing Influence of News",
    description:
      "A Task 2 two-part essay about why the news has become more influential and whether this is positive or negative.",
    prompt:
      "The news has an increasing impact on people's lives and has never been this influential before.\nWhy is this the case? Is this a positive or negative development?",
    image: "",
    htmlFile: "/writing/task2_23.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_24",
    task: 2,
    type: "Agree/Disagree",
    title: "Museums and National Culture",
    description:
      "A Task 2 essay about whether museums and galleries should focus mainly on national history and culture.",
    prompt:
      "Museums and art galleries should concentrate on works that show the history and culture of their own country rather than works from other parts of the world.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_24.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_25",
    task: 2,
    type: "Problem/Solution",
    title: "Exercise and Older People",
    description:
      "A Task 2 cause-and-solution essay about why elderly people may not exercise enough and how to encourage them.",
    prompt: "Many old people do not get enough exercise.\nWhy? What can be done?",
    image: "",
    htmlFile: "/writing/task2_25.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_26",
    task: 2,
    type: "Discussion",
    title: "Technology and Crime",
    description:
      "A Task 2 discussion essay about whether technology reduces crime or creates new opportunities for crime.",
    prompt:
      "Some people think technology development decreases crimes, while others believe it actually encourages crimes.\nDiscuss both views and give your own opinion.",
    image: "",
    htmlFile: "/writing/task2_26.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_27",
    task: 2,
    type: "Agree/Disagree",
    title: "Producing Food Locally",
    description:
      "A Task 2 essay about whether countries should produce most of their own food and reduce food imports.",
    prompt:
      "Some people suggest that a country should try to produce all the food for its population and import as little food as possible.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_27.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_28",
    task: 2,
    type: "Agree/Disagree",
    title: "Social Skills and Qualifications",
    description:
      "A Task 2 essay about whether social skills are as important as qualifications for success at work.",
    prompt:
      "Many employers are employing people with good social skills as well as good qualifications.\nDo you agree or disagree that good social skills are as important as good qualifications to succeed in a job?",
    image: "",
    htmlFile: "/writing/task2_28.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_29",
    task: 2,
    type: "Agree/Disagree",
    title: "Free University Education",
    description:
      "A Task 2 essay about whether university education should be free for everyone regardless of financial background.",
    prompt:
      "Some people believe that university education should be free, as everyone has a right to study regardless of financial background.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_29.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_30",
    task: 2,
    type: "Problem/Solution",
    title: "Food Waste Around the World",
    description:
      "A Task 2 essay about why millions of tons of food are wasted globally and how this problem can be solved.",
    prompt:
      "Every day, millions of tons of food are wasted all over the world.\nWhy do you think this is happening?\nAnd how can we solve this problem?",
    image: "",
    htmlFile: "/writing/task2_30.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_31",
    task: 2,
    type: "Agree/Disagree",
    title: "Traditional Food and Fast Food",
    description:
      "A Task 2 essay about whether replacing traditional food with international fast food negatively affects families and society.",
    prompt:
      "In many countries, traditional food is being replaced by international fast food. Some people claim that this has negative effects on both families and society.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_31.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_32",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Private Scientific Research",
    description:
      "A Task 2 essay about whether private companies funding and conducting scientific research has more advantages than disadvantages.",
    prompt:
      "In today's world, private companies rather than the government pay for and conduct most scientific research.\nDo you think the advantages outweigh the disadvantages?",
    image: "",
    htmlFile: "/writing/task2_32.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_33",
    task: 2,
    type: "Agree/Disagree",
    title: "Are Libraries Still Important?",
    description:
      "A Task 2 essay about whether libraries have become unnecessary due to online access to information.",
    prompt:
      "Nowadays, many people think that libraries are no longer important because people can access information online.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_33.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_34",
    task: 2,
    type: "Agree/Disagree",
    title: "Libraries vs Online Information",
    description:
      "A Task 2 essay about whether libraries are still necessary given that students can access information online.",
    prompt:
      "Students today can easily access information online, so libraries are no longer necessary.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_34.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_35",
    task: 2,
    type: "Agree/Disagree",
    title: "Employee Dress Code",
    description:
      "A Task 2 essay about whether employers should care about how their employees dress at work.",
    prompt:
      "Some people think that employers should not care about the way their employees dress because what matters is the quality of their work.\nTo what extent do you agree or disagree with this statement?",
    image: "",
    htmlFile: "/writing/task2_35.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_36",
    task: 2,
    type: "Agree/Disagree",
    title: "Space Exploration Funding",
    description:
      "A Task 2 essay about whether money spent on space exploration is a waste and should instead improve lives on Earth.",
    prompt:
      "Spending money on space exploration is a waste of time. Instead, funds should be spent on improving people's lives on Earth.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_36.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_37",
    task: 2,
    type: "Problem/Solution",
    title: "Elderly Loneliness and Poor Health",
    description:
      "A Task 2 essay examining the causes of loneliness and poor health among elderly people and possible solutions.",
    prompt:
      "Some research shows that older people are generally happier and healthier if they remain active. However, many elderly people today suffer from loneliness and poor physical health.\nWhat are the causes of this trend, and what measures can be taken to solve this problem?",
    image: "",
    htmlFile: "/writing/task2_37.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_38",
    task: 2,
    type: "Discussion",
    title: "Printed Books vs Digital Storage",
    description:
      "A Task 2 essay discussing whether printed books are still necessary in the digital age.",
    prompt:
      "Some people think that printed books are no longer necessary in this digital era as all writing can be stored electronically. Others think that printed books still play an important role.\nDiscuss both views and give your opinion.",
    image: "",
    htmlFile: "/writing/task2_38.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_39",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Private Healthcare",
    description:
      "A Task 2 essay about whether the advantages of private health care outweigh the disadvantages.",
    prompt:
      "Some people think that good health is a basic human need, so medical services should not be run by profit-making companies.\nDo the advantages of private health care outweigh the disadvantages?",
    image: "",
    htmlFile: "/writing/task2_39.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_40",
    task: 2,
    type: "Agree/Disagree",
    title: "Government Spending on Sport and Art",
    description:
      "A Task 2 essay about whether governments should fund sport and art in schools or invest in professional events instead.",
    prompt:
      "Some people think that the government should spend money on children to take part in sport and art classes in schools, while others think they should spend on professional sports events and public art performances.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_40.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_41",
    task: 2,
    type: "Discussion",
    title: "Junk Food and Education",
    description:
      "A Task 2 essay discussing whether education is an effective solution to the problem of junk food consumption.",
    prompt:
      "Scientists agree that people are damaging their health by eating too much junk food. Some people think that the answer to this problem is to educate people. Others think education will not work.\nDiscuss both views and give your own opinion.",
    image: "",
    htmlFile: "/writing/task2_41.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_42",
    task: 2,
    type: "Agree/Disagree",
    title: "Is Scientific Research a Waste?",
    description:
      "A Task 2 essay about whether modern scientific research is a waste of time and money.",
    prompt:
      "Some people believe that scientific research done today is a waste of time and money.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_42.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_43",
    task: 2,
    type: "Direct Question",
    title: "What Arts Tell Us About Life",
    description:
      "A Task 2 essay exploring what the arts can reveal about life that science and technology cannot.",
    prompt:
      "In today's world of advanced science and technology, we still greatly value our artists such as musicians, painters and writers.\nWhat can arts tell us about life that science and technology cannot?",
    image: "",
    htmlFile: "/writing/task2_43.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_44",
    task: 2,
    type: "Problem/Solution",
    title: "The Throwaway Culture",
    description:
      "A Task 2 essay about why people today throw away broken items instead of repairing them, and the problems this causes.",
    prompt:
      "In many parts of the world, people now often throw things away when they are broken and buy new ones, whereas in the past broken things were repaired and used again.\nWhy do you think this is the case? What problems may it lead to?",
    image: "",
    htmlFile: "/writing/task2_44.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_45",
    task: 2,
    type: "Agree/Disagree",
    title: "Traditional Ideas of Older Generations",
    description:
      "A Task 2 essay about whether traditional ideas held by older generations are unhelpful for preparing young people for modern life.",
    prompt:
      "The older generations tend to have very traditional ideas about how people should live, think and behave. However, some people believe that these ideas are not helpful in preparing younger generations for modern life.\nTo what extent do you agree or disagree with this view?",
    image: "",
    htmlFile: "/writing/task2_45.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_46",
    task: 2,
    type: "Problem/Solution",
    title: "Unhealthy Lifestyles",
    description:
      "A Task 2 essay about why people continue unhealthy activities despite knowing the risks, and how to address this.",
    prompt:
      "Scientists tell us some activities are good for health and others are bad. Despite knowing that, millions of people continue doing unhealthy activities.\nWhat are the causes and what are the solutions?",
    image: "",
    htmlFile: "/writing/task2_46.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_47",
    task: 2,
    type: "Discussion",
    title: "University vs Getting a Job",
    description:
      "A Task 2 essay discussing whether university is the best path to a successful career or whether starting work after school is better.",
    prompt:
      "Some people believe that studying at university or college is the best route to a successful career, while others believe that it is better to get a job straight after school.\nDiscuss both views and give your opinion.",
    image: "",
    htmlFile: "/writing/task2_47.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_48",
    task: 2,
    type: "Agree/Disagree",
    title: "Olympic Spending vs Youth Sports",
    description:
      "A Task 2 essay about whether money spent on elite sporting competitions should instead be used to encourage children to take up sport.",
    prompt:
      "Some countries spend a lot of money preparing competitors to take part in major competitions such as the Olympic Games or the Football World Cup. Some people say that it would be better to spend this money encouraging children to take up sports from a young age.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_48.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_49",
    task: 2,
    type: "Agree/Disagree",
    title: "Following Customs in a New Country",
    description:
      "A Task 2 essay about whether immigrants should follow the customs and traditions of their new country.",
    prompt:
      "People should follow the customs and traditions when they start to live in a new country.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_49.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_50",
    task: 2,
    type: "Positive/Negative Development",
    title: "Spending on Looking Younger",
    description:
      "A Task 2 essay about why people spend money to look younger and whether this is a positive or negative development.",
    prompt:
      "More and more people today are spending large amounts of money on their appearance in order to look younger. Why do people want to look younger?\nDo you think this is a positive or negative development?",
    image: "",
    htmlFile: "/writing/task2_50.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_51",
    task: 2,
    type: "Agree/Disagree",
    title: "Local History vs World History",
    description:
      "A Task 2 essay about whether it is more important for schoolchildren to study local history than world history.",
    prompt:
      "It is more important for schoolchildren to learn about local history than world history.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_51.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_52",
    task: 2,
    type: "Agree/Disagree",
    title: "Purpose of Schools",
    description:
      "A Task 2 essay about whether schools should focus on producing good citizens and workers rather than benefiting students as individuals.",
    prompt:
      "Some people think that the main purpose of schools is to turn children into good citizens and workers, rather than to benefit them as individuals.\nTo what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_52.html",
    minWords: 250,
    timeMinutes: 40,
  },
  {
    id: "task2_53",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Credit Cards and Debt",
    description:
      "A Task 2 essay about whether the advantages of easily available credit cards outweigh the disadvantages.",
    image: "",
    htmlFile: "/writing/task2_53.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_54",
    task: 2,
    type: "Discussion",
    title: "Government Control of Food Choices",
    description:
      "A Task 2 discussion essay about whether the government should regulate people's nutrition and food choices or leave it to personal responsibility.",
    image: "",
    htmlFile: "/writing/task2_54.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_55",
    task: 2,
    type: "Two-Part Question",
    title: "Rising Demand for University Education",
    description:
      "A Task 2 two-part essay about why more people want to attend university and whether this is a positive or negative development.",
    image: "",
    htmlFile: "/writing/task2_55.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_56",
    task: 2,
    type: "Discussion",
    title: "Government Control of Fresh Water",
    description:
      "A Task 2 discussion essay about whether the government should strictly control the supply of fresh water or leave it unregulated.",
    image: "",
    htmlFile: "/writing/task2_56.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_57",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Working Abroad with Family",
    description:
      "A Task 2 essay about whether the advantages of moving abroad for work and taking one's family outweigh the disadvantages.",
    image: "",
    htmlFile: "/writing/task2_57.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_58",
    task: 2,
    type: "Agree/Disagree",
    title: "Pay for Professionals vs Entertainers",
    description:
      "A Task 2 essay about whether professionals such as doctors, nurses and teachers should be paid more than sports and entertainment personalities.",
    image: "",
    htmlFile: "/writing/task2_58.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_59",
    task: 2,
    type: "Two-Part Question",
    title: "Having Children Late in Life",
    description:
      "A Task 2 essay about the reasons people have children later in life and the effects on society and family life.",
    image: "",
    htmlFile: "/writing/task2_59.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },
  {
    id: "task2_60",
    task: 2,
    type: "Positive/Negative Development",
    title: "Living Alone vs Extended Families",
    description:
      "A Task 2 essay about whether the trend towards living alone or in small family units rather than extended families is a positive or negative development.",
    image: "",
    htmlFile: "/writing/task2_60.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
  },

  // ── IELTS CDI Report – additional Writing Task 1 simulators ──
  {
    id: "html-t1-australian-zoo-1990-vs-now",
    task: 1,
    type: "Map",
    title: "Australian Zoo: 1990 vs Now",
    description: "The maps below show an Australian zoo in 1990 and now.",
    image: "/writing-images/task1_26.jpg",
    htmlFile: "/passages/task1_26.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-holidaymakers-accommodation-types",
    task: 1,
    type: "Pie Chart",
    title: "Holidaymakers' Accommodation Types",
    description: "The charts below show the proportion of holidaymakers using four different types of accommodations in three different years.",
    image: "/writing-images/task1_27.jpg",
    htmlFile: "/passages/task1_27.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-us-government-research-spending",
    task: 1,
    type: "Line Graph",
    title: "US Government Research Spending",
    description: "The graph below gives information about U.S. government spending on research between 1980 and 2000.",
    image: "/writing-images/task1_28.jpg",
    htmlFile: "/passages/task1_28.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-football-match-attendance-in-europe",
    task: 1,
    type: "Line Graph",
    title: "Football Match Attendance in Europe",
    description: "The line graph shows the average number of people attending top-level football matches in three European countries from 1980 to 2004.",
    image: "/writing-images/task1_29.jpg",
    htmlFile: "/passages/task1_29.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-actual-vs-expected-city-populations",
    task: 1,
    type: "Bar Chart",
    title: "Actual vs Expected City Populations",
    description: "The chart shows information about the actual and expected figures of population in three cities.",
    image: "/writing-images/task1_30.jpg",
    htmlFile: "/passages/task1_30.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-silk-production-in-england-and-wales",
    task: 1,
    type: "Table",
    title: "Silk Production in England and Wales",
    description: "The table shows the number of employees and factories producing silk in England and Wales between 1851 and 1901.",
    image: "/writing-images/task1_31.jpg",
    htmlFile: "/passages/task1_31.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-bridgetown-1700-vs-2000",
    task: 1,
    type: "Map",
    title: "Bridgetown: 1700 vs 2000",
    description: "The diagrams below show the changes of a town called Bridgetown in 1700 and 2000.",
    image: "/writing-images/task1_32.jpg",
    htmlFile: "/passages/task1_32.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-electricity-consumption-in-eastern-europe",
    task: 1,
    type: "Bar Chart",
    title: "Electricity Consumption in Eastern Europe",
    description: "The chart below shows the electricity consumption in different sectors of Eastern Europe in 2007 and 2010.",
    image: "/writing-images/task1_33.jpg",
    htmlFile: "/passages/task1_33.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-university-salaries-and-fees",
    task: 1,
    type: "Bar Chart",
    title: "University Salaries and Fees",
    description: "The bar charts give information about the salaries and university fees of students from three universities in two spheres-Law and Business",
    image: "/writing-images/task1_34.jpg",
    htmlFile: "/passages/task1_34.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-ryemouth-village-1995-vs-present",
    task: 1,
    type: "Map",
    title: "Ryemouth Village: 1995 vs Present",
    description: "The maps show the village of Ryemouth between 1995 and present.",
    image: "/writing-images/task1_35.jpg",
    htmlFile: "/passages/task1_35.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-healthcare-satisfaction-in-four-countries",
    task: 1,
    type: "Line Graph",
    title: "Healthcare Satisfaction in Four Countries",
    description: "The graph below shows people's level of satisfaction with the health care system in 4 countries between 1991 and 2007.",
    image: "/writing-images/task1_36.jpg",
    htmlFile: "/passages/task1_36.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-student-course-types-over-time",
    task: 1,
    type: "Pie Chart",
    title: "Student Course Types Over Time",
    description: "The pie charts below show the different types of courses, which were followed by the students during the years of 1984, 1994 and 2004.",
    image: "/writing-images/task1_37.jpg",
    htmlFile: "/passages/task1_37.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-walton-museum-south-wing-redevelopment",
    task: 1,
    type: "Map",
    title: "Walton Museum South Wing Redevelopment",
    description: "The plans below show the South Wing of Walton Museum in 2008 and in 2012 after it was redeveloped.",
    image: "/writing-images/task1_38.jpg",
    htmlFile: "/passages/task1_38.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-trips-by-men-and-women",
    task: 1,
    type: "Bar Chart",
    title: "Trips by Men and Women",
    description: "The chart gives information about the number and purposes of trips made by men and women in one year in a certain European country.",
    image: "/writing-images/task1_39.jpg",
    htmlFile: "/passages/task1_39.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-village-development-1910-vs-2010",
    task: 1,
    type: "Map",
    title: "Village Development: 1910 vs 2010",
    description: "The maps below show part of a village in 1910, and the same part of that village in 2010.",
    image: "/writing-images/task1_40.jpg",
    htmlFile: "/passages/task1_40.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-household-spending-in-europe",
    task: 1,
    type: "Pie Chart",
    title: "Household Spending in Europe",
    description: "The charts below show the proportion of people’s total spending on different commodities and services in a particular European country in 1998 and 2008",
    image: "/writing-images/task1_41.jpg",
    htmlFile: "/passages/task1_41.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-australian-school-leavers-destinations",
    task: 1,
    type: "Bar Chart",
    title: "Australian School Leavers' Destinations",
    description: "The charts show the Australian school leavers did immediately after leaving secondary school.",
    image: "/writing-images/task1_42.jpg",
    htmlFile: "/passages/task1_42.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-cinema-attendance-by-age-group",
    task: 1,
    type: "Line Graph",
    title: "Cinema Attendance by Age Group",
    description: "The graph shows the percentage of visiting the cinema once a month or more between 1984 to 2003(4 age groups)",
    image: "/writing-images/task1_43.jpg",
    htmlFile: "/passages/task1_43.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-students-across-university-departments",
    task: 1,
    type: "Table",
    title: "Students Across University Departments",
    description: "The table shows the percentage of students in six different departments in 2011.",
    image: "/writing-images/task1_44.jpg",
    htmlFile: "/passages/task1_44.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-music-event-attendance-in-australia",
    task: 1,
    type: "Bar Chart",
    title: "Music Event Attendance in Australia",
    description: "The bar chart shows the percentage of attendance for three types of music events in 2006 in Australia.",
    image: "/writing-images/task1_45.jpg",
    htmlFile: "/passages/task1_45.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-income-and-poverty-in-three-us-states",
    task: 1,
    type: "Table",
    title: "Income and Poverty in Three US States",
    description: "The table below shows information about age, average income per person and population below the poverty line in three states in the USA.",
    image: "/writing-images/task1_46.jpg",
    htmlFile: "/passages/task1_46.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-weekly-food-consumption-in-europe",
    task: 1,
    type: "Table",
    title: "Weekly Food Consumption in Europe",
    description: "The table shows weekly food consumption by one European country in 1992, 2002 and 2012.",
    image: "/writing-images/task1_47.jpg",
    htmlFile: "/passages/task1_47.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-share-of-world-population-by-country",
    task: 1,
    type: "Line Graph",
    title: "Share of World Population by Country",
    description: "The chart below shows the percentage of whole world population in four countries from 1950 to 2000, with projections till 2050.",
    image: "/writing-images/task1_48.jpg",
    htmlFile: "/passages/task1_48.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-uk-residents-trips-abroad",
    task: 1,
    type: "Mixed",
    title: "UK Residents' Trips Abroad",
    description: "The line graph and the table show the number of trips to other countries by UK residents for various purposes between 1989 and 2001.",
    image: "/writing-images/task1_49.jpg",
    htmlFile: "/passages/task1_49.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-how-carbonated-drinks-are-made",
    task: 1,
    type: "Process",
    title: "How Carbonated Drinks Are Made",
    description: "The diagram gives information about the process of making carbonated drinks.",
    image: "/writing-images/task1_50.jpg",
    htmlFile: "/passages/task1_50.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-telephone-and-internet-use-in-china",
    task: 1,
    type: "Line Graph",
    title: "Telephone and Internet Use in China",
    description: "The graph below describes the use of fixed telephone lines, mobile phones, and internet between 1994 and 2005 in China.",
    image: "/writing-images/task1_51.jpg",
    htmlFile: "/passages/task1_51.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },
  {
    id: "html-t1-films-released-and-ticket-sales-1996-2006",
    task: 1,
    type: "Bar Chart",
    title: "Films Released and Cinema Ticket Sales",
    description: "The graphs below show the total percentage of films released and the total percentage of ticket sales in 1996 and 2006 in a country.",
    image: "/writing-images/task1_52.jpg",
    htmlFile: "/passages/task1_52.html",
    minWords: 150,
    timeMinutes: 20,
    isNew: true,
    isFree: true,
  },

  // ── IELTS CDI Report – additional Writing Task 2 simulators ──
  {
    id: "task2_61",
    task: 2,
    type: "Agree/Disagree",
    title: "Investing in Young People",
    description: "A Task 2 essay: The best way for a government to prepare for the future is to invest resources in its young people. To what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_61.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_62",
    task: 2,
    type: "Agree/Disagree",
    title: "Housing Shortages and Government Action",
    description: "A Task 2 essay: Housing shortages in big cities can cause severe social consequences. Some people think only government action can solve this problem. To what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_62.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_63",
    task: 2,
    type: "Discussion",
    title: "Broad vs Specialised Study",
    description: "A Task 2 essay: Some people think that it is better for older schoolchildren to study a large number of subjects and develop a range of knowledge. Others argue that they should study a smaller number of subjects and focus in details. Discuss both views and give your opinion.",
    image: "",
    htmlFile: "/writing/task2_63.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_64",
    task: 2,
    type: "Discussion",
    title: "Climate Change and Business",
    description: "A Task 2 essay: Some people think that climate change could have a negative effect on business. Other people think that climate change could create more business opportunities. Discuss both views and give your own opinion.",
    image: "",
    htmlFile: "/writing/task2_64.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_65",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Gap Years Before University",
    description: "A Task 2 essay: Some school leavers travel or work for a period of time instead of going directly to university. What are the advantages or disadvantages for their study?",
    image: "",
    htmlFile: "/writing/task2_65.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_66",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Studying Abroad: Benefits vs Problems",
    description: "A Task 2 essay: Today, more and more students are choosing to move to a different country for higher studies. Do you think the benefits of this outweigh the problems?",
    image: "",
    htmlFile: "/writing/task2_66.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_67",
    task: 2,
    type: "Advantages/Disadvantages",
    title: "Peer Pressure: Advantages vs Disadvantages",
    description: "A Task 2 essay: Children are influenced by their peers in their behaviour and attitudes. This is called peer group pressure. Do the advantages of peer pressure outweigh disadvantages?",
    image: "",
    htmlFile: "/writing/task2_67.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_68",
    task: 2,
    type: "Agree/Disagree",
    title: "Annual Driving Tests and Road Safety",
    description: "A Task 2 essay: Some people think that the best way to improve road safety is to get drivers tested each year. To what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_68.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_69",
    task: 2,
    type: "Direct Question",
    title: "Admiring Media and Sports Stars",
    description: "A Task 2 essay: Nowadays, young people are admiring media and sports stars, even though they do not set a good example. Do you think this is a positive or negative development?",
    image: "",
    htmlFile: "/writing/task2_69.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_70",
    task: 2,
    type: "Discussion",
    title: "What Determines Success in Life",
    description: "A Task 2 essay: Some people believe that success in life depends on hard work and determination, while others believe that other factors such as money and personal appearance are more important. Discuss both views and give your own opinion.",
    image: "",
    htmlFile: "/writing/task2_70.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_71",
    task: 2,
    type: "Agree/Disagree",
    title: "Imprisonment vs Education for Crime",
    description: "A Task 2 essay: In many countries, imprisonment is the most common solution to crime. However, some people believe that better education will be effective solution. To what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_71.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_72",
    task: 2,
    type: "Problem/Solution",
    title: "Money Management for Students",
    description: "A Task 2 essay: Students leave high school without learning the way how to manage their money. What are the reasons and solutions for this issue?",
    image: "",
    htmlFile: "/writing/task2_72.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_73",
    task: 2,
    type: "Agree/Disagree",
    title: "Exploiting Undiscovered Resources",
    description: "A Task 2 essay: With the increased global demand for oil and gas, undiscovered areas of the world should be opened up to access more resources. To what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_73.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_74",
    task: 2,
    type: "Discussion",
    title: "Studying in Groups vs Alone",
    description: "A Task 2 essay: Some people think that it is more effective for students to study in a group while others believe that it is better for them to study alone. Discuss both views and give your opinion",
    image: "",
    htmlFile: "/writing/task2_74.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_75",
    task: 2,
    type: "Agree/Disagree",
    title: "City Living and Health",
    description: "A Task 2 essay: Living in big cities is bad for people's health. To what extent do you agree or disagree with this opinion?",
    image: "",
    htmlFile: "/writing/task2_75.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_76",
    task: 2,
    type: "Discussion",
    title: "TV's Influence on Children",
    description: "A Task 2 essay: Some people think that the amount of time children spend on TV influences their behaviour, while others argue that what they watch has the greatest influence. Discuss both views and give your opinion.",
    image: "",
    htmlFile: "/writing/task2_76.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_77",
    task: 2,
    type: "Agree/Disagree",
    title: "Petrol Prices, Traffic and the Environment",
    description: "A Task 2 essay: Some people believe that increasing the price of petrol is the best way to solve growing traffic and environmental problems. To what extent do you agree or disagree?",
    image: "",
    htmlFile: "/writing/task2_77.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_78",
    task: 2,
    type: "Direct Question",
    title: "Computer Games vs Sports for Children",
    description: "A Task 2 essay: Many children spend a lot of time playing computer games and less time doing sports. Why is this? Is it a positive or negative development?",
    image: "",
    htmlFile: "/writing/task2_78.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
  {
    id: "task2_79",
    task: 2,
    type: "Discussion",
    title: "Causes of Crime: Circumstance or Nature",
    description: "A Task 2 essay: Some people think crimes are the result of circumstances like poverty and other social problems. Others believe that they are caused by people who are bad in nature. Discuss both views and give your opinion.",
    image: "",
    htmlFile: "/writing/task2_79.html",
    minWords: 250,
    timeMinutes: 40,
    isNew: true,
    isFree: true,
  },
];
