/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ListeningRouteImport } from './routes/listening'
import { Route as ContactAboutRouteImport } from './routes/contact-about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingTaskIdRouteImport } from './routes/writing.$taskId'
import { Route as SpeakingTopicsExplainedRouteImport } from './routes/speaking_.topics-explained'
import { Route as SpeakingPronunciationRouteImport } from './routes/speaking_.pronunciation'
import { Route as ArticlesSlugRouteImport } from './routes/articles_.$slug'
import { Route as WritingSampleIdRouteImport } from './routes/writing_.sample.$id'
import { Route as WritingEssayIdRouteImport } from './routes/writing_.essay.$id'
import { Route as WritingTaskIdPracticeRouteImport } from './routes/writing.$taskId.practice'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningRoute = ListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactAboutRoute = ContactAboutRouteImport.update({
  id: '/contact-about',
  path: '/contact-about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingTaskIdRoute = WritingTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => WritingRoute,
} as any)
const SpeakingTopicsExplainedRoute = SpeakingTopicsExplainedRouteImport.update({
  id: '/speaking_/topics-explained',
  path: '/speaking/topics-explained',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingPronunciationRoute = SpeakingPronunciationRouteImport.update({
  id: '/speaking_/pronunciation',
  path: '/speaking/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles_/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSampleIdRoute = WritingSampleIdRouteImport.update({
  id: '/writing_/sample/$id',
  path: '/writing/sample/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingEssayIdRoute = WritingEssayIdRouteImport.update({
  id: '/writing_/essay/$id',
  path: '/writing/essay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingTaskIdPracticeRoute = WritingTaskIdPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => WritingTaskIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/contact-about': typeof ContactAboutRoute
  '/listening': typeof ListeningRoute
  '/practice': typeof PracticeRoute
  '/premium': typeof PremiumRoute
  '/reading': typeof ReadingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/speaking': typeof SpeakingRoute
  '/videos': typeof VideosRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/speaking/pronunciation': typeof SpeakingPronunciationRoute
  '/speaking/topics-explained': typeof SpeakingTopicsExplainedRoute
  '/writing/$taskId': typeof WritingTaskIdRouteWithChildren
  '/writing/$taskId/practice': typeof WritingTaskIdPracticeRoute
  '/writing/essay/$id': typeof WritingEssayIdRoute
  '/writing/sample/$id': typeof WritingSampleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/contact-about': typeof ContactAboutRoute
  '/listening': typeof ListeningRoute
  '/practice': typeof PracticeRoute
  '/premium': typeof PremiumRoute
  '/reading': typeof ReadingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/speaking': typeof SpeakingRoute
  '/videos': typeof VideosRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/speaking/pronunciation': typeof SpeakingPronunciationRoute
  '/speaking/topics-explained': typeof SpeakingTopicsExplainedRoute
  '/writing/$taskId': typeof WritingTaskIdRouteWithChildren
  '/writing/$taskId/practice': typeof WritingTaskIdPracticeRoute
  '/writing/essay/$id': typeof WritingEssayIdRoute
  '/writing/sample/$id': typeof WritingSampleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/contact-about': typeof ContactAboutRoute
  '/listening': typeof ListeningRoute
  '/practice': typeof PracticeRoute
  '/premium': typeof PremiumRoute
  '/reading': typeof ReadingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/speaking': typeof SpeakingRoute
  '/videos': typeof VideosRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRouteWithChildren
  '/articles_/$slug': typeof ArticlesSlugRoute
  '/speaking_/pronunciation': typeof SpeakingPronunciationRoute
  '/speaking_/topics-explained': typeof SpeakingTopicsExplainedRoute
  '/writing/$taskId': typeof WritingTaskIdRouteWithChildren
  '/writing/$taskId/practice': typeof WritingTaskIdPracticeRoute
  '/writing_/essay/$id': typeof WritingEssayIdRoute
  '/writing_/sample/$id': typeof WritingSampleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/contact-about'
    | '/listening'
    | '/practice'
    | '/premium'
    | '/reading'
    | '/reset-password'
    | '/speaking'
    | '/videos'
    | '/vocabulary'
    | '/writing'
    | '/articles/$slug'
    | '/speaking/pronunciation'
    | '/speaking/topics-explained'
    | '/writing/$taskId'
    | '/writing/$taskId/practice'
    | '/writing/essay/$id'
    | '/writing/sample/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/contact-about'
    | '/listening'
    | '/practice'
    | '/premium'
    | '/reading'
    | '/reset-password'
    | '/speaking'
    | '/videos'
    | '/vocabulary'
    | '/writing'
    | '/articles/$slug'
    | '/speaking/pronunciation'
    | '/speaking/topics-explained'
    | '/writing/$taskId'
    | '/writing/$taskId/practice'
    | '/writing/essay/$id'
    | '/writing/sample/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/contact-about'
    | '/listening'
    | '/practice'
    | '/premium'
    | '/reading'
    | '/reset-password'
    | '/speaking'
    | '/videos'
    | '/vocabulary'
    | '/writing'
    | '/articles_/$slug'
    | '/speaking_/pronunciation'
    | '/speaking_/topics-explained'
    | '/writing/$taskId'
    | '/writing/$taskId/practice'
    | '/writing_/essay/$id'
    | '/writing_/sample/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ArticlesRoute: typeof ArticlesRoute
  AuthRoute: typeof AuthRoute
  ContactAboutRoute: typeof ContactAboutRoute
  ListeningRoute: typeof ListeningRoute
  PracticeRoute: typeof PracticeRoute
  PremiumRoute: typeof PremiumRoute
  ReadingRoute: typeof ReadingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SpeakingRoute: typeof SpeakingRoute
  VideosRoute: typeof VideosRoute
  VocabularyRoute: typeof VocabularyRoute
  WritingRoute: typeof WritingRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  SpeakingPronunciationRoute: typeof SpeakingPronunciationRoute
  SpeakingTopicsExplainedRoute: typeof SpeakingTopicsExplainedRoute
  WritingEssayIdRoute: typeof WritingEssayIdRoute
  WritingSampleIdRoute: typeof WritingSampleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening': {
      id: '/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof ListeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-about': {
      id: '/contact-about'
      path: '/contact-about'
      fullPath: '/contact-about'
      preLoaderRoute: typeof ContactAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$taskId': {
      id: '/writing/$taskId'
      path: '/$taskId'
      fullPath: '/writing/$taskId'
      preLoaderRoute: typeof WritingTaskIdRouteImport
      parentRoute: typeof WritingRoute
    }
    '/speaking_/topics-explained': {
      id: '/speaking_/topics-explained'
      path: '/speaking/topics-explained'
      fullPath: '/speaking/topics-explained'
      preLoaderRoute: typeof SpeakingTopicsExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking_/pronunciation': {
      id: '/speaking_/pronunciation'
      path: '/speaking/pronunciation'
      fullPath: '/speaking/pronunciation'
      preLoaderRoute: typeof SpeakingPronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/$slug': {
      id: '/articles_/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing_/sample/$id': {
      id: '/writing_/sample/$id'
      path: '/writing/sample/$id'
      fullPath: '/writing/sample/$id'
      preLoaderRoute: typeof WritingSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing_/essay/$id': {
      id: '/writing_/essay/$id'
      path: '/writing/essay/$id'
      fullPath: '/writing/essay/$id'
      preLoaderRoute: typeof WritingEssayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$taskId/practice': {
      id: '/writing/$taskId/practice'
      path: '/practice'
      fullPath: '/writing/$taskId/practice'
      preLoaderRoute: typeof WritingTaskIdPracticeRouteImport
      parentRoute: typeof WritingTaskIdRoute
    }
  }
}

interface WritingTaskIdRouteChildren {
  WritingTaskIdPracticeRoute: typeof WritingTaskIdPracticeRoute
}

const WritingTaskIdRouteChildren: WritingTaskIdRouteChildren = {
  WritingTaskIdPracticeRoute: WritingTaskIdPracticeRoute,
}

const WritingTaskIdRouteWithChildren = WritingTaskIdRoute._addFileChildren(
  WritingTaskIdRouteChildren,
)

interface WritingRouteChildren {
  WritingTaskIdRoute: typeof WritingTaskIdRouteWithChildren
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingTaskIdRoute: WritingTaskIdRouteWithChildren,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ArticlesRoute: ArticlesRoute,
  AuthRoute: AuthRoute,
  ContactAboutRoute: ContactAboutRoute,
  ListeningRoute: ListeningRoute,
  PracticeRoute: PracticeRoute,
  PremiumRoute: PremiumRoute,
  ReadingRoute: ReadingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SpeakingRoute: SpeakingRoute,
  VideosRoute: VideosRoute,
  VocabularyRoute: VocabularyRoute,
  WritingRoute: WritingRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
  SpeakingPronunciationRoute: SpeakingPronunciationRoute,
  SpeakingTopicsExplainedRoute: SpeakingTopicsExplainedRoute,
  WritingEssayIdRoute: WritingEssayIdRoute,
  WritingSampleIdRoute: WritingSampleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
